// Custom RGB Matrix configuration
#ifdef RGB_MATRIX_CUSTOM_USER
#   define RGB_MATRIX_CUSTOM_EFFECTS
#   define ENABLE_RGB_MATRIX_BLUE_HEATMAP
#   define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#   define RGB_MATRIX_KEYPRESSES
#   define RGB_MATRIX_HUE_STEP 8
#   define RGB_MATRIX_SAT_STEP 8
#   define RGB_MATRIX_VAL_STEP 8
#   define RGB_MATRIX_SPD_STEP 10
#   define DRIVER_LED_TOTAL 54
#   define RGB_MATRIX_SPLIT { 27, 27 }
#   define SPLIT_TRANSPORT_MIRROR
#endif

#define RGB_MATRIX_BLUE_HEATMAP 50

// OLED configuration
#ifdef OLED_ENABLE
#   define SPLIT_OLED_ENABLE
#   define OLED_TIMEOUT 30000  // 30 Seconds
#   define OLED_TASK_KB_OVERRIDE
#endif
