RGB_MATRIX_ENABLE = yes
AUTOCORRECT_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
BOOTMAGIC_ENABLE = no
TAP_DANCE_ENABLE = no
ONESHOT_ENABLE = no
UNICODE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

NO_DEBUG = yes
NO_PRINT = yes
