# Feature Configuration
RGB_MATRIX_ENABLE = yes
AUTOCORRECT_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
BOOTMAGIC_ENABLE = no
TAP_DANCE_ENABLE = no
ONESHOT_ENABLE = no
UNICODE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

# Disable Unused RGBLight Modes
ENABLE_RGB_MATRIX_ALPHAS_MODS = no
ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN = no
ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT = no
ENABLE_RGB_MATRIX_BREATHING = no
ENABLE_RGB_MATRIX_BAND_SAT = no
ENABLE_RGB_MATRIX_BAND_VAL = no
ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT = no
ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL = no
ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT = no
ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL = no
ENABLE_RGB_MATRIX_CYCLE_ALL = no
ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT = no
ENABLE_RGB_MATRIX_CYCLE_UP_DOWN = no
ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON = no
ENABLE_RGB_MATRIX_CYCLE_OUT_IN = no
ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL = no
ENABLE_RGB_MATRIX_CYCLE_PINWHEEL = no
ENABLE_RGB_MATRIX_CYCLE_SPIRAL = no
ENABLE_RGB_MATRIX_DUAL_BEACON = no
ENABLE_RGB_MATRIX_RAINBOW_BEACON = no
ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS = no
ENABLE_RGB_MATRIX_RAINDROPS = no
ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS = no
ENABLE_RGB_MATRIX_HUE_BREATHING = no
ENABLE_RGB_MATRIX_HUE_PENDULUM = no
ENABLE_RGB_MATRIX_HUE_WAVE = no
ENABLE_RGB_MATRIX_PIXEL_RAIN = no
ENABLE_RGB_MATRIX_PIXEL_FLOW = no
ENABLE_RGB_MATRIX_PIXEL_FRACTAL = no
ENABLE_RGB_MATRIX_DIGITAL_RAIN = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS = no
ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS = no
ENABLE_RGB_MATRIX_SPLASH = no
ENABLE_RGB_MATRIX_MULTISPLASH = no
ENABLE_RGB_MATRIX_SOLID_SPLASH = no
ENABLE_RGB_MATRIX_SOLID_MULTISPLASH = no

# Custom Source Files
SRC += oled.c

# Optimization Settings
LINK_TIME_OPTIMIZATION_ENABLE = yes
EXTRAFLAGS += -flto

# Disable Unused Features
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

NO_DEBUG = yes
NO_PRINT = yes
