#define DEBUG

#define TAPPING_TERM 200  // 200ms tapping term

#define RGBLIGHT_SAT_STEP 8    // Controls the saturation change step
#define RGBLIGHT_VAL_STEP 8    // Controls the value change step

#undef RGBLIGHT_MODE_BREATHING_1
#undef RGBLIGHT_MODE_BREATHING_2
#undef RGBLIGHT_MODE_BREATHING_3
#undef RGBLIGHT_MODE_RAINBOW_MOOD_1
#undef RGBLIGHT_MODE_RAINBOW_MOOD_2
#undef RGBLIGHT_MODE_RAINBOW_SWIRL_0
#undef RGBLIGHT_MODE_RAINBOW_SWIRL_1
#undef RGBLIGHT_MODE_RAINBOW_SWIRL_2
#undef RGBLIGHT_MODE_RAINBOW_SWIRL_3
#undef RGBLIGHT_MODE_RAINBOW_SWIRL_4
#undef RGBLIGHT_MODE_SNAKE
#undef RGBLIGHT_MODE_STATIC_GRADIENT_0
#undef RGBLIGHT_MODE_STATIC_GRADIENT_1
#undef RGBLIGHT_MODE_STATIC_GRADIENT_2
#undef RGBLIGHT_MODE_STATIC_GRADIENT_3
#undef RGBLIGHT_MODE_STATIC_GRADIENT_4
#undef RGBLIGHT_MODE_STATIC_GRADIENT_5
#undef RGBLIGHT_MODE_STATIC_GRADIENT_6
#undef RGBLIGHT_MODE_STATIC_GRADIENT_7
#undef RGBLIGHT_MODE_STATIC_GRADIENT_8
#undef RGBLIGHT_MODE_RGB_TEST
#undef RGBLIGHT_MODE_ALTERNATING
