#include QMK_KEYBOARD_H
#include "keycode_utils.h"

// Define a struct for keycode-to-name mapping
typedef struct {
    uint16_t keycode;
    const char* name;
} keycode_map_t;

// Create a lookup table for keycodes and their names
static const keycode_map_t keycode_map[] = {
    {KC_ESC, "KC_ESC"},
    {KC_1, "KC_1"},
    {KC_2, "KC_2"},
    {KC_3, "KC_3"},
    {KC_4, "KC_4"},
    {KC_5, "KC_5"},
    {KC_6, "KC_6"},
    {KC_7, "KC_7"},
    {KC_8, "KC_8"},
    {KC_9, "KC_9"},
    {KC_0, "KC_0"},
    {KC_MINS, "KC_MINS"},
    {KC_TAB, "KC_TAB"},
    {KC_Q, "KC_Q"},
    {KC_W, "KC_W"},
    {KC_E, "KC_E"},
    {KC_R, "KC_R"},
    {KC_T, "KC_T"},
    {KC_Y, "KC_Y"},
    {KC_U, "KC_U"},
    {KC_I, "KC_I"},
    {KC_O, "KC_O"},
    {KC_P, "KC_P"},
    {KC_LBRC, "KC_LBRC"},
    {KC_LCTL, "KC_LCTL"},
    {KC_A, "KC_A"},
    {KC_S, "KC_S"},
    {KC_D, "KC_D"},
    {KC_F, "KC_F"},
    {KC_G, "KC_G"},
    {KC_H, "KC_H"},
    {KC_J, "KC_J"},
    {KC_K, "KC_K"},
    {KC_L, "KC_L"},
    {KC_SCLN, "KC_SCLN"},
    {KC_QUOT, "KC_QUOT"},
    {KC_RBRC, "KC_RBRC"},
    {KC_LSFT, "KC_LSFT"},
    {KC_Z, "KC_Z"},
    {KC_X, "KC_X"},
    {KC_C, "KC_C"},
    {KC_V, "KC_V"},
    {KC_B, "KC_B"},
    {KC_N, "KC_N"},
    {KC_M, "KC_M"},
    {KC_COMM, "KC_COMM"},
    {KC_DOT, "KC_DOT"},
    {KC_SLSH, "KC_SLSH"},
    {KC_BSLS, "KC_BSLS"},
    {KC_RALT, "KC_RALT"},
    {KC_SPC, "KC_SPC"},
    {KC_ENT, "KC_ENT"},
    {KC_BSPC, "KC_BSPC"},
    {KC_LWIN, "KC_LWIN"},
    {KC_F1, "KC_F1"},
    {KC_F2, "KC_F2"},
    {KC_F3, "KC_F3"},
    {KC_F4, "KC_F4"},
    {KC_F5, "KC_F5"},
    {KC_F6, "KC_F6"},
    {KC_F7, "KC_F7"},
    {KC_F8, "KC_F8"},
    {KC_F9, "KC_F9"},
    {KC_F10, "KC_F10"},
    {KC_F11, "KC_F11"},
    {KC_F12, "KC_F12"},
    {KC_TILD, "KC_TILD"},
    {KC_EXLM, "KC_EXLM"},
    {KC_AT, "KC_AT"},
    {KC_HASH, "KC_HASH"},
    {KC_DLR, "KC_DLR"},
    {KC_PERC, "KC_PERC"},
    {KC_CIRC, "KC_CIRC"},
    {KC_AMPR, "KC_AMPR"},
    {KC_ASTR, "KC_ASTR"},
    {KC_LPRN, "KC_LPRN"},
    {KC_RPRN, "KC_RPRN"},
    {KC_EQL, "KC_EQL"},
    {KC_GRV, "KC_GRV"},
    {KC_UNDS, "KC_UNDS"},
    {KC_PLUS, "KC_PLUS"},
    {KC_LCBR, "KC_LCBR"},
    {KC_RCBR, "KC_RCBR"},
    {KC_PIPE, "KC_PIPE"},
    {KC_UP, "KC_UP"},
    {KC_DOWN, "KC_DOWN"},
    {KC_LEFT, "KC_LEFT"},
    {KC_RIGHT, "KC_RIGHT"},
    {KC_DEL, "KC_DEL"},
    {KC_HOME, "KC_HOME"},
    {KC_END, "KC_END"},
    {KC_INS, "KC_INS"},
    {XXXXXXX, "KC_NO"},
    {_______, "KC_TRNS"},
    {RGB_TOG, "RGB_TOG"},
    {UG_VALD, "UG_VALD"},
    {UG_VALU, "UG_VALU"},
    {UG_SATD, "UG_SATD"},
    {UG_SATU, "UG_SATU"},
    {UG_HUED, "UG_HUED"},
    {UG_HUEU, "UG_HUEU"},
    {UG_PREV, "UG_PREV"},
    {UG_NEXT, "UG_NEXT"},
    {UG_SPDD, "UG_SPDD"},
    {UG_SPDU, "UG_SPDU"},
    {EE_CLR, "EE_CLR"},
};

// Function to get the name of a keycode
const char* get_keycode_name(uint16_t keycode) {
    for (size_t i = 0; i < sizeof(keycode_map) / sizeof(keycode_map[0]); i++) {
        if (keycode_map[i].keycode == keycode) {
            return keycode_map[i].name;
        }
    }
    return "UNKNOWN";
}
