CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = yes
OLED_ENABLE = yes
LINK_TIME_OPTIMIZATION_ENABLE = yes

EXTRAFLAGS += -flto

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
