# Feature Configuration
TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = yes
OLED_ENABLE = yes
SLEEP_ENABLE = no
WPM_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no

# Disable Unused RGBLight Modes
RGBLIGHT_EFFECT_BREATHING = no
# RGBLIGHT_EFFECT_RAINBOW_MOOD = no
RGBLIGHT_EFFECT_RAINBOW_SWIRL = no
RGBLIGHT_EFFECT_SNAKE = no
RGBLIGHT_MODE_KNIGHT = no
RGBLIGHT_MODE_CHRISTMAS = no
RGBLIGHT_EFFECT_STATIC_GRADIENT = no
RGBLIGHT_EFFECT_RGB_TEST = no
RGBLIGHT_EFFECT_ALTERNATING = no

# Custom Source Files
SRC += oled.c
SRC += oled_state.c

# Optimization Settings
LINK_TIME_OPTIMIZATION_ENABLE = yes
EXTRAFLAGS += -flto

# Disable Unused Features
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
